name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: make bootstrap
      - name: Run lint checks
        run: make lint
      - name: Run tests
        run: make test